name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pipenv dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.local/share/virtualenvs
          ~/.cache/pipenv
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Check code formatting with black
      run: |
        pipenv run black --check .

    - name: Run pytest
      run: |
        pipenv run pytest
